### ISSUE TITLE
Show GUI by default?

### ISSUE THREAD

**Issue by FuZeEclipse** [Cybermaxke/StatsGui#1]
My apologies if this was the wrong place to put this but I would really like to see this plugin have a feature to enable it by default. Also, maybe some color customization to the menu would be nice :)

**Comment by Cybermaxke** [comment]
I already added in the last update. If you join for the first time, it will show by default.
Your choice will be saved for the next joins.

**Comment by FuZeEclipse** [comment]
Could you possibly give us a download to the newer version? I would just compile the source but I'm not on my computer right now.

**Comment by Cybermaxke** [comment]
I am now updating it for 1.5.1, once I am finished I will add a new download and post it also in the comments.
