### ISSUE TITLE
NullPointer exception

### ISSUE THREAD

**Issue by tescz** [Cybermaxke/StatsGui#10]
Hi, 
MCMMO version: 1.4.0.6-dev2-b1918
Bukkit version: 1.5.1-R0.3 build #2757
McMMOStatsGui version: 1.4

http://pastebin.com/hnAp9LGE

**Comment by zrocweb** [comment]
bad pastebin id... repaste..... not sure if max recompiled with the latest Cb build or not which I'm sure (haven't checked) yet if it change the GUI API calls.

**Comment by Cybermaxke** [comment]
Should be fixed after the latest changes.
