### ISSUE TITLE
Stats Gui Problem

### ISSUE THREAD

**Issue by DistortedDorian** [Cybermaxke/StatsGui#11]
Hey, i got a problem, when im opped and fight a cow it change the stats gui to

Unarmed
Required XP  [xp]
Earbed XP [xp]
Level [level]

But when im deopped its not showing it, what is the problem?
And for permission node: mcMMOStatsGui.UseSkillGui.SKILL, where can i find a list of all skills?

**Comment by zrocweb** [comment]
skills are:
unarmed
swords
axes
herbalism
fishing
mining
repair
smelting
woodcutting
excavation
powerlevel
taming

**Comment by Cybermaxke** [comment]
Can be found at this page: https://github.com/Cybermaxke/mcMMOStatsGui/wiki/What-are-the-skill-types%3F
