### ISSUE TITLE
Disable Skills in the list.

### ISSUE THREAD

**Issue by jjacobson** [Cybermaxke/StatsGui#3]
Hello, is there a way to disable the skills in the list? I try negating mcMMOStatsGui.UseSkillGui.mining, but mining still shows on the list of skills. If you could add a way to remove skills from the list that would be awesome, as many servers dont use each skill.

**Comment by Cybermaxke** [comment]
This will be fixed in the next release, changes are already pushed. :)

**Comment by jjacobson** [comment]
Any way you can post a download? I am updating my server tonight and adding this would be awesome!

**Comment by zrocweb** [comment]
Max added this and it is pending.. stick tight!!!

**Comment by parisfuja** [comment]
cool plugin

**Comment by Cybermaxke** [comment]
In the new update: use negative permissions because everything is shown by default.
