### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PillageCraft** [Cybermaxke/StatsGui#4]
Version of Plugin: 1.4
Version of CraftBukkit: Latest development build for 1.5.1

Error: http://pastie.org/7138758

**Comment by zrocweb** [comment]
What other plugins are you running. How much memory do u have on your server.  What build of CB are you running?

**Comment by XxCoolGamesxX** [comment]
In the error he send say at <code>[SEVERE] java.lang.OutOfMemoryError: Java heap space</code> at mean can be is Ram die of space. But yes PillageCraft you it to give more info. Of your server. : D

**Comment by zrocweb** [comment]
What version of Java.  Seems like you are not running Java 7 (1.7) and should be..

**Comment by Cybermaxke** [comment]
Hopefully fixed this.
