### ISSUE TITLE
Error with GUI

### ISSUE THREAD

**Issue by cyatness** [Cybermaxke/StatsGui#6]
Running CB 1.5 R0.1 for MC 1.5.1
GUI doesn't show up by default and when I do the command to show it, I get an error message that tells me an internal error has occurred.
These are the errors I saw in the console when I ran the command.

30.03 15:59:41 [Server] INFO at net.minecraft.server.v1_5_R1.PlayerList.a(PlayerList.java:100)
30.03 15:59:41 [Server] INFO at net.minecraft.server.v1_5_R1.PlayerList.c(PlayerList.java:204)
30.03 15:59:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
30.03 15:59:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
30.03 15:59:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
30.03 15:59:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
30.03 15:59:41 [Server] INFO org.bukkit.event.EventException
30.03 15:59:41 [Server] SEVERE Could not pass event PlayerJoinEvent to mcMMOStats v1.4

**Comment by XxCoolGamesxX** [comment]
It you update your Mcmmo plugin ?

**Comment by cyatness** [comment]
Yes I did, should I update it to the latest beta/dev build?

**Comment by XxCoolGamesxX** [comment]
Yes, Sure download the latest dev build. Because in the mcMMOStats v1.4 only work on the 1.5.1 of craftbukkit. Not the 1.5. : D

**Comment by cyatness** [comment]
Still not working :( 
Here is a full error list.

30.03 16:29:43 [Server] INFO ... 15 more
30.03 16:29:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.03 16:29:43 [Server] INFO at me.cybermaxke.mcmmostats.GuiCommand.onCommand(GuiCommand.java:59)
30.03 16:29:43 [Server] INFO Caused by: java.lang.NullPointerException
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:409)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.MinecraftServer.q(MinecraftServer.java:476)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.DedicatedServer.r(DedicatedServer.java:225)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.MinecraftServer.r(MinecraftServer.java:580)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.DedicatedServerConnection.b(SourceFile:30)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.ServerConnection.b(SourceFile:35)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.PlayerConnection.d(PlayerConnection.java:113)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.NetworkManager.b(NetworkManager.java:292)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.Packet3Chat.handle(Packet3Chat.java:44)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.PlayerConnection.a(PlayerConnection.java:840)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.PlayerConnection.chat(PlayerConnection.java:885)
30.03 16:29:43 [Server] INFO at net.minecraft.server.v1_5_R1.PlayerConnection.handleCommand(PlayerConnection.java:967)
30.03 16:29:43 [Server] INFO at org.bukkit.craftbukkit.v1_5_R1.CraftServer.dispatchCommand(CraftServer.java:514)
30.03 16:29:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
30.03 16:29:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
30.03 16:29:43 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'statsgui' in plugin mcMMOStats v1.4
30.03 16:29:43 [Server] SEVERE null

**Comment by zrocweb** [comment]
From the errors above, you are running an older version of the statsGUI.  the craftbukit.v1_5_R1 should be R2 as coded in the plugin which make direct calls to those APIs.  Try to donwload the recent file again and ensure you kill whatever one u have on your server first. then upload the downloaded version to your server again and try again.

**Comment by XxCoolGamesxX** [comment]
Make it easy you it to download is one http://dl.bukkit.org/downloads/craftbukkit/view/02027_1.5.1-R0.1/

**Comment by cyatness** [comment]
THANKYOU SO MUCH GUYS!!!! <3

**Comment by XxCoolGamesxX** [comment]
Nope : D

**Comment by cyatness** [comment]
One more thing... It works for me no (I'm OP), but no one else. I set the permissions for it to work by default and also the one that allows them to use the command. I still get the internal error when I use the command.

**Comment by zrocweb** [comment]
can you re-paste your complete log to see whats going on?

**Comment by cyatness** [comment]
30.03 17:22:40 [Server] INFO ... 15 more
30.03 17:22:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.03 17:22:40 [Server] INFO at me.cybermaxke.mcmmostats.GuiCommand.onCommand(GuiCommand.java:59)
30.03 17:22:40 [Server] INFO Caused by: java.lang.NullPointerException
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:578)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.Packet3Chat.handle(Packet3Chat.java:44)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:841)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.PlayerConnection.chat(PlayerConnection.java:884)
30.03 17:22:40 [Server] INFO at net.minecraft.server.v1_5_R2.PlayerConnection.handleCommand(PlayerConnection.java:966)
30.03 17:22:40 [Server] INFO at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchCommand(CraftServer.java:523)
30.03 17:22:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:187)
30.03 17:22:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
30.03 17:22:40 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'statsgui' in plugin mcMMOStats v1.4
30.03 17:22:40 [Server] SEVERE null

**Comment by zrocweb** [comment]
can you tell me what the command is u used. this is saying what you type was null and/or does not match that of what is expected.  the command is (lowercase) /statsgui <hide | show>

**Comment by cyatness** [comment]
/statsgui show or /statsgui hide both yeild the same error

**Comment by XxCoolGamesxX** [comment]
It you download the latest dev build of mcmmo is not here the link: http://ci.mcmmo.org/job/mcMMO/1852/artifact/target/mcMMO.jar

**Comment by zrocweb** [comment]
what version of mcMMO are u running.  at least 1.3.11+

**Comment by XxCoolGamesxX** [comment]
I think he use old mcmmo. I test it on my test server with the new dev mcmmo and craftbukkit.

**Comment by cyatness** [comment]
It works now since I updated the mcMMO
Thanks a bunch guys

**Comment by XxCoolGamesxX** [comment]
See Nope you have Fun with the plugin. ; D
