### ISSUE TITLE
Plugin gives internal server error

### ISSUE THREAD

**Issue by melodicaxe** [Cybermaxke/StatsGui#7]
http://pastebin.com/1aJWTgfz here is the error
I am running this plugin version mcMMOStatsGui v1.4 for 1.5.1
I am running on 1.5.1 craftbukkit

**Comment by XxCoolGamesxX** [comment]
It you update your mcmmo ?

**Comment by melodicaxe** [comment]
works like a charm

**Comment by XxCoolGamesxX** [comment]
Happy for you : D
