### ISSUE TITLE
McMMO / McMMO Stats Event Error.

### ISSUE THREAD

**Issue by ghost** [Cybermaxke/StatsGui#9]
I'm getting this issue right here, particularly when i hit players, sometimes on occasions when players actually hit me, i believe it has to deal with players gaining 4x the regular XP amount with McMMO.

Error Log: -> http://pastebin.com/jxZ4Yz8p

CB Version:-> http://i.imgur.com/rnyEPvV.png

The issue could be that i'm running a newer version of Bukkit compared to the builds that McMMOStatsGui is currently updated for.

**Comment by zrocweb** [comment]
What version of mcMMO are you using

**Comment by Cybermaxke** [comment]
Should be fixed.
